services:
  db:
    image: postgres:16
    container_name: agenda_db
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: agenda
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
